[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run preview -- --host 0.0.0.0 --port $PORT --strictPort"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[service]
schedule = "0 */6 * * *"  # Runs every 6 hours 